### PR TITLE
Fix changeset helper to use casted embedded struct

### LINKED ISSUE #162: MCQ answer returned as string instead of number
#### Steps to reproduce
- Authenticate
- Request for an Assessment with an answered mcq question

I'm getting this: 
image

### PR DESCRIPTION
**Pull request by tuesmiddt**
Fixes #162 

For context, `answer: %{choice_id: "1"}` can be validly cast with a `field(:choice_id, :integer)` so it passes validation, but this will not be reflected in the original changeset.

### CODE REVIEW

File: lib/cadet/assessments/assessments.ex [hunk 1]
```diff
@@ -291,15 +291,18 @@ defmodule Cadet.Assessments do
...
+      |> Answer.changeset(%{
+        answer: answer_content,
+        question_id: question.id,
+        submission_id: submission.id,
+        type: question.type
+      })
+
+    Repo.insert(
+      answer_changeset,
+      on_conflict: [set: [answer: get_change(answer_changeset, :answer)]],
```
Comment (indocomsoft) [inline lib/cadet/assessments/assessments.ex]: Not sure what's the difference compared to the previous one?

Comment (indocomsoft) [reply lib/cadet/assessments/assessments.ex]: Ahh ok I see.
